export const FETCH_ISSUES_START = 'FETCH_ISSUES_START';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';

export const UPVOTE_ISSUE_START = 'UPVOTE_ISSUE_START';
export const UPVOTE_ISSUE_SUCCESS = 'UPVOTE_ISSUE_SUCCESS';

export const DELETE_ISSUE_START = 'DELETE_ISSUE_START';
export const DELETE_ISSUE_SUCCESS = 'DELETE_ISSUE_SUCCESS';